services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:8080"
    environment:
      PGADMIN_DEFAULT_EMAIL: akash@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 8080
    depends_on:
      - postgres

# Define named volumes