spring:
  application:
    name: waycourier
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: waycourier
  security:
    user:
      name: admin
      password: admin