spring:
  application:
    name: waycourier
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27018
      database: packages
      username: admin
      password: password
  security:
    user:
      name: admin
      password: admin